---

- hosts: "{{ instance_ip}}"
  vars:
    remote_home_dir: "/home/ubuntu"

  tasks:
   - name: update apt
     apt:
       upgrade: yes
       update_cache: yes
     become: yes

   - name : install packages
     apt:
       name: "{{ item }}"
       state: latest
     with_items:
       - python3-pip
       - python3-dev
       - build-essential
       - libssl-dev
       - libffi-dev
       - python3-setuptools
       - python3-venv
       - python3
     become: yes

   - name: create directory
     file:
       path: "{{remote_home_dir}}/myproject"
       state: directory
       mode: '0755'

   - name : copy python files to remote host
     copy :
       src: "{{ playbook_dir }}/../python/{{ item }}"
       dest: "{{ remote_home_dir }}/myproject/"
     with_items:
       - calculator.py
       - test_calculator.py

   - name: create virtual env
     command: python3 -m venv myprojectenv
     args:
      chdir: "{{ remote_home_dir }}/myproject"

   - name: virtual env activate
     shell: source ~/myproject/myprojectenv/bin/activate
     args:
       executable: /bin/bash

   - name: pip install flask
     pip:
       name: "{{ item }}"
       state: latest
     with_items:
       - wheel
       - flask
       - request

   - name: running python
     command: python calculator.py
     args:
        chdir: "{{ remote_home_dir }}/myproject"
